version: "3"

services:
    project-data:
        build:
            dockerfile: Dockerfile
            context: .
            args:
                REACT_APP_CONFIG_HOST: ${REACT_APP_CONFIG_HOST}
                REACT_APP_ADAPTER_HOST: ${REACT_APP_ADAPTER_HOST}
        ports:
            - ${HOST_PORT:-3000}:3000
